var qs = ["Kako se zove najviša planina u Škotskoj?",
"Koja je najduža rijeka koja u cjelosti protječe samo Europom?",
"Kako se zove najveći poluotok na kojem se nalazi Danska?",
"Koliko država ima obalu na Crnom moru?",
"Koji je najveći otok u Sredozmenom moru?",
"Koja je najveća planina što se djelom nalazi u Pakistanu?",
"Koja je najmanja država u Aziji?",
"S koliko država graniči Kina?",
"Koja je azijska država površinom najbliže površini Kaspijskog jezera?",
"Imena koliko država u Aziji završavaju na -stan?",
"Koja je druga najduža rijeka Južne Amerike?",
"Kako se zove najviši vrh Čilea?",
"Koliko država čini kontinent Južne Amerike?",
"Koje je najviše jezero u Južnoj Americi na kojem je dopuštena plovidba?",
"Koja država Južne Amerike ima najlošiji BDP po stanovniku?",
"Koji je najveći zaljev Sjeverne Amerike?",
"Koja je najmanja država Sjeverne Amerike?",
"U koliko je zemalja Sjeverne Amerike portugalski službeni jezik?",
"Kako se zove najviši vrh Kanade?",
"Na koliko se provincija dijeli Kanada?",
"Koliko država spada pod kontinent Australija?",
"Koliko se afričkih država nalazi u cijelosti unutar neke druge države?",
"Na koliko je provincija podjeljena Australija?",
"Koliko afričkih država ima veću površinu od površine otoka Grenlanda?",
"Koja afrička država ima najviše stanovnika?",
"Kako se zove najduža rijeka u Australiji?",
"Kako se zove najveće afričko jezero?",
"Kako se zove najviši vrh Australije?",
"Koliko država posjeduje određene djelove Anktartike?",
"Koji je najviši vrh Anktartike?",
"Koje je vrste najviše stablo na svijetu?",
"Koji cvijet može imati promjer od 2 milimetra do 3 metra?",
"Koja je najbrže rastuća biljka na svijetu?",
"Koliko otprilike različitih vrsta jabuka postoji?",
"Koliko otprilike poznatih biljnih vrsta postoji na zemlji?",
"Koji je naziv za carstvo biljaka?",
"Koju biljku predstavlja naziv Taraxacum?",
"Kako se zovu biljke koje prevladavaju na području močvara?",
"Koliko zaštićenih biljnih vrsta nalazimo u Hrvatskoj?",
"Koji je hrvatski otok iznimno bogat rijetkim biljkama i endemima?",
"Koja je najbrža kopnena životinja na svijetu?",
"Koliko se različitih životinja nalazi u grbu Republike Hrvatske?",
"Koja se životinja najčešće može naći na grbovima?",
"Kako se zove najmanja ptica na svijetu?",
"Koja životinja ima 32 'mozga' ?",
"Koji pauk plete najsnažniju mrežu na svijetu?",
"Koja životinja jede isključivo naopačke?",
"Kako se zove ptica koja je ime dobila prema portugalskoj riječi za budalu?",
"Kojih je vrsta životinja otkriveno preko 1 000 000?",
"Kako se zove riba koja ne može narasti više od 8 milimetara?",
"Koliko organskih sustava čini ljudski organizam?",
"Koji je najveći organ ljudskoga tijela?",
"Kako se zove najmanja kost u čovijeku?",
"Koliko mišića postoji u ljudskom tijelu?",
"Koliko kralježaka ima čovijek?",
"Koja je boja očiju najčešća u ljudi?",
"Koliko otprilike litara iznosi ukupni kapacitet pluća?",
"Koliko centimetara iznosi visina najvišeg čovijeka na svijetu ikada?",
"Koju kost predstavlja naziv Radius",
"Koji je najzastupljeniji element u ljudskom tijelu?",
"Kako se zvao prvi gradonačelnik grada Zagreba?",
"Kako se zove mjesto u kojem je pronađena Bašćanska ploča?",
"Koje se godine odigrala bitka s Tatarima na Grobničkom polju?",
"Koje godine Ivan Kukuljević Sakcinski održao poznati govor u saboru?",
"Koje je godine Ante Starčević utemeljio Stranku prava?",
"Koliko je godina postojala Dubrovačka Republika?",
"Kako se zove pogranično područje organizirano kao obrambeni pojas?",
"Koji je bio glavni grad Kneževine Panonske Hrvatske?",
"Koliko je crveno-bijelih polja imao grb Hrvatsko-Ugarskog  kraljevstva?",
"Kojeg je datuma 1990. godine donesen prvi hrvatski ustav?",
"Koje je godine prije Krista ubijen Gaj Julije Cezar?",
"Sedam rimskih brežuljaka: Eksvilin, Kvirinal, Viminal, Celij, Kapitolij, Aventin i … ?",
"Kako se zvao otac Karla i Karlomana što su 768. godine podjelili Franačku?",
"Koje je godine Henrik VIII. osnovao Anglikansku crkvu?",
"Kako se zvala utvrda koja je pala 14. srpnja 1789. godine?",
"Napoleon je poražen 1813. godine u bitci kod kojega grada?",
"Kojeg je datuma 1918. godine započela Ofenziva od 100 dana?",
"Kako se zove poluotok na kojem započinje Drugi svjetski rat 1. rujna 1939. godine?",
"Kojeg je datuma 1945. godine službeno potpisana kapitulacija Japana?",
"Kojeg je datuma uvedena jedinstvena europska valuta - Euro?",
"Koje je godine usvojen ustav SAD-a?",
"Koji je američki predsjednik provodio politiku velike batine?",
"Kako se zove prvo englesko naselje na području SAD-a?",
"Koje je godine Južni Sudan postao neovisan?",
"Koje je godine Nelson Mandela izabran za predsjednika?",
"Koja je država do 1999. godine upravljala Posebnom upravnom regijom Makao?",
"Koja je država proglasila nezavisnost od Indije 1971. godine?",
"Koje je godine prvi puta otkriven dio Anktartike?",
"Kako se zove osoba koja je 1788. sa 11 brodova uplovila u Botany Bay?",
"Kako se nazivaju starosjedioci Novog Zelanda?",
"Tko je osvojio zlatnu loptu 2007. godine?",
"Kako se zove trener koji je osvojio Ligu prvaka 2010. godine?",
"Koji igrač drži rekord po broju zabijenih golova u jednoj sezoni engleske Premier Lige?",
"Tko je osvojio svjetsko prvenstvo 1994. godine?",
"Koje godine je Urugvaj posljednji put osvojio Svjetsko prvenstvo?",
"Koji klub ima najviše osvojenih FA kupova?",
"Koji igrač drži rekord za najviše zabijenih golova u Ligi prvaka?",
"Tko je najviše puta nosio kapetansku traku Hrvatske?",
"Koja država ima najviše osvojenih Copa America?",
"Koji igrač je zaradio najviše crvenih kartona na Europskim prvenstvima?",
"Tko ima najviše osvojenih Australian Opena?",
"Koja je država najviše puta bila finalist Davis Cupa?",
"Koje je godine Marin Čilić osvojio US Open?",
"Koliko naslova Roland Garrosa ima Rafael Nadal?",
"Koliko je puta Goran Ivanišević bio u finalu Wimbeldona?",
"Koja je najviša pozicija na ATP ljestvici do koje je dospio neki hrvatski tenisač?",
"Tko je osvojio ATP Finals 2019. godine?",
"Koja hrvatska tenisačica ima osvojen juniorski US Open i Australian Open?",
"Koliko puta je Hrvatska osvojila Hopman Cup?",
"Koliko ukupno WTA naslova ima Serena Williams?"]

var qst = ["Kako se zove najviša planina u Škotskoj?",
"Koja je najduža rijeka koja u cjelosti protječe samo Europom?",
"Kako se zove najveći poluotok na kojem se nalazi Danska?",
"Koliko država ima obalu na Crnom moru?",
"Koji je najveći otok u Sredozmenom moru?",
"Koja je najveća planina što se djelom nalazi u Pakistanu?",
"Koja je najmanja država u Aziji?",
"S koliko država graniči Kina?",
"Koja je azijska država površinom najbliže površini Kaspijskog jezera?",
"Imena koliko država u Aziji završavaju na -stan?",
"Koja je druga najduža rijeka Južne Amerike?",
"Kako se zove najviši vrh Čilea?",
"Koliko država čini kontinent Južne Amerike?",
"Koje je najviše jezero u Južnoj Americi na kojem je dopuštena plovidba?",
"Koja država Južne Amerike ima najlošiji BDP po stanovniku?",
"Koji je najveći zaljev Sjeverne Amerike?",
"Koja je najmanja država Sjeverne Amerike?",
"U koliko je zemalja Sjeverne Amerike portugalski službeni jezik?",
"Kako se zove najviši vrh Kanade?",
"Na koliko se provincija dijeli Kanada?",
"Koliko država spada pod kontinent Australija?",
"Koliko se afričkih država nalazi u cijelosti unutar neke druge države?",
"Na koliko je provincija podjeljena Australija?",
"Koliko afričkih država ima veću površinu od površine otoka Grenlanda?",
"Koja afrička država ima najviše stanovnika?",
"Kako se zove najduža rijeka u Australiji?",
"Kako se zove najveće afričko jezero?",
"Kako se zove najviši vrh Australije?",
"Koliko država posjeduje određene djelove Anktartike?",
"Koji je najviši vrh Anktartike?",
"Koje je vrste najviše stablo na svijetu?",
"Koji cvijet može imati promjer od 2 milimetra do 3 metra?",
"Koja je najbrže rastuća biljka na svijetu?",
"Koliko otprilike različitih vrsta jabuka postoji?",
"Koliko otprilike poznatih biljnih vrsta postoji na zemlji?",
"Koji je naziv za carstvo biljaka?",
"Koju biljku predstavlja naziv Taraxacum?",
"Kako se zovu biljke koje prevladavaju na području močvara?",
"Koliko zaštićenih biljnih vrsta nalazimo u Hrvatskoj?",
"Koji je hrvatski otok iznimno bogat rijetkim biljkama i endemima?",
"Koja je najbrža kopnena životinja na svijetu?",
"Koliko se različitih životinja nalazi u grbu Republike Hrvatske?",
"Koja se životinja najčešće može naći na grbovima?",
"Kako se zove najmanja ptica na svijetu?",
"Koja životinja ima 32 'mozga' ?",
"Koji pauk plete najsnažniju mrežu na svijetu?",
"Koja životinja jede isključivo naopačke?",
"Kako se zove ptica koja je ime dobila prema portugalskoj riječi za budalu?",
"Kojih je vrsta životinja otkriveno preko 1 000 000?",
"Kako se zove riba koja ne može narasti više od 8 milimetara?",
"Koliko organskih sustava čini ljudski organizam?",
"Koji je najveći organ ljudskoga tijela?",
"Kako se zove najmanja kost u čovijeku?",
"Koliko mišića postoji u ljudskom tijelu?",
"Koliko kralježaka ima čovijek?",
"Koja je boja očiju najčešća u ljudi?",
"Koliko otprilike litara iznosi ukupni kapacitet pluća?",
"Koliko centimetara iznosi visina najvišeg čovijeka na svijetu ikada?",
"Koju kost predstavlja naziv Radius",
"Koji je najzastupljeniji element u ljudskom tijelu?",
"Kako se zvao prvi gradonačelnik grada Zagreba?",
"Kako se zove mjesto u kojem je pronađena Bašćanska ploča?",
"Koje se godine odigrala bitka s Tatarima na Grobničkom polju?",
"Koje godine Ivan Kukuljević Sakcinski održao poznati govor u saboru?",
"Koje je godine Ante Starčević utemeljio Stranku prava?",
"Koliko je godina postojala Dubrovačka Republika?",
"Kako se zove pogranično područje organizirano kao obrambeni pojas?",
"Koji je bio glavni grad Kneževine Panonske Hrvatske?",
"Koliko je crveno-bijelih polja imao grb Hrvatsko-Ugarskog  kraljevstva?",
"Kojeg je datuma 1990. godine donesen prvi hrvatski ustav?",
"Koje je godine prije Krista ubijen Gaj Julije Cezar?",
"Sedam rimskih brežuljaka: Eksvilin, Kvirinal, Viminal, Celij, Kapitolij, Aventin i … ?",
"Kako se zvao otac Karla i Karlomana što su 768. godine podjelili Franačku?",
"Koje je godine Henrik VIII. osnovao Anglikansku crkvu?",
"Kako se zvala utvrda koja je pala 14. srpnja 1789. godine?",
"Napoleon je poražen 1813. godine u bitci kod kojega grada?",
"Kojeg je datuma 1918. godine započela Ofenziva od 100 dana?",
"Kako se zove poluotok na kojem započinje Drugi svjetski rat 1. rujna 1939. godine?",
"Kojeg je datuma 1945. godine službeno potpisana kapitulacija Japana?",
"Kojeg je datuma uvedena jedinstvena europska valuta - Euro?",
"Koje je godine usvojen ustav SAD-a?",
"Koji je američki predsjednik provodio politiku velike batine?",
"Kako se zove prvo englesko naselje na području SAD-a?",
"Koje je godine Južni Sudan postao neovisan?",
"Koje je godine Nelson Mandela izabran za predsjednika?",
"Koja je država do 1999. godine upravljala Posebnom upravnom regijom Makao?",
"Koja je država proglasila nezavisnost od Indije 1971. godine?",
"Koje je godine prvi puta otkriven dio Anktartike?",
"Kako se zove osoba koja je 1788. sa 11 brodova uplovila u Botany Bay?",
"Kako se nazivaju starosjedioci Novog Zelanda?",
"Tko je osvojio zlatnu loptu 2007. godine?",
"Kako se zove trener koji je osvojio Ligu prvaka 2010. godine?",
"Koji igrač drži rekord po broju zabijenih golova u jednoj sezoni engleske Premier Lige?",
"Tko je osvojio svjetsko prvenstvo 1994. godine?",
"Koje godine je Urugvaj posljednji put osvojio Svjetsko prvenstvo?",
"Koji klub ima najviše osvojenih FA kupova?",
"Koji igrač drži rekord za najviše zabijenih golova u Ligi prvaka?",
"Tko je najviše puta nosio kapetansku traku Hrvatske?",
"Koja država ima najviše osvojenih Copa America?",
"Koji igrač je zaradio najviše crvenih kartona na Europskim prvenstvima?",
"Tko ima najviše osvojenih Australian Opena?",
"Koja je država najviše puta bila finalist Davis Cupa?",
"Koje je godine Marin Čilić osvojio US Open?",
"Koliko naslova Roland Garrosa ima Rafael Nadal?",
"Koliko je puta Goran Ivanišević bio u finalu Wimbeldona?",
"Koja je najviša pozicija na ATP ljestvici do koje je dospio neki hrvatski tenisač?",
"Tko je osvojio ATP Finals 2019. godine?",
"Koja hrvatska tenisačica ima osvojen juniorski US Open i Australian Open?",
"Koliko puta je Hrvatska osvojila Hopman Cup?",
"Koliko ukupno WTA naslova ima Serena Williams?"]

var as = ["Ben Nevis",
"Dunav",
"Jylland",
"5",
"Sicilija",
"K2",
"Bahrein",
"14",
"Japan",
"7",
"Parana",
"Aconcagua",
"13",
"Titicaca",
"Bolivija",
"Meksički zaljev",
"Sveti Kristofor i Nevis",
"0",
"Mount Logan",
"10",
"14",
"2",
"7",
"2",
"Nigerija",
"Murray",
"Viktorijino jezero",
"Mount Kosciuszko",
"6",
"Vinstonov Massif",
"sekvoja",
"orhideja",
"bambus",
"7000",
"300000",
"Plantae",
"maslačak",
"helofiti",
"760",
"Palagruža",
"gepard",
"3",
"lav",
"kolibrić",
"pijavica",
"Darwinov pauk",
"flamingo",
"Dodo",
"kukaca",
"Pandaka",
"11",
"koža",
"stremen",
"752",
"33",
"smeđa",
"6",
"272",
"palčanu kost",
"ugljik",
"Janko Kamauf",
"Jurandvor",
"1242.",
"1843.",
"1861.",
"450",
"Vojna krajina",
"Sisak",
"16",
"22. prosinca",
"44. godine",
"Palatin",
"Pipin Mali",
"1531. godine",
"Bastilia",
"Leipziga",
"8. kolovoza",
"Westerplatte",
"2. rujna",
"1. siječnja 2002.",
"1787. godine",
"Theodore Roosevelt",
"Jamestown",
"2011. godine",
"1994. godine",
"Portugal",
"Bangladeš",
"1739. godine",
"Arthur Phillip",
"Maori",
"Kaka",
"Jose Mourinho",
"Mohamed Salah",
"Brazil",
"1950. godine",
"Arsenal",
"Cristiano Ronaldo",
"Darijo Srna",
"Urugvaj",
"Radoslav Latal",
"Novak Đoković",
"Sjedinjene Američke države",
"2014. godine",
"12",
"4",
"2.",
"Stefanos Tsitsipas",
"Ana Konjuh",
"1",
"72"]

var score = 0;
var done = 0;

function show(){
	if (qs.length > 0){
		var x = Math.floor(Math.random()*qs.length);
		document.getElementById("ques").innerHTML = qs[x];
		qs.splice(x,1)

		document.getElementById("ans").disabled = false;
	}
	else{
		document.getElementById("ques").innerHTML = "Za ovu kategoriju više nema pitanja u bazi. Osvježite stranicu kako biste krenuli ispočetka ili se okušajte u nekoj od ostalih kategorija"
		document.getElementById("fontup").innerHTML = "Nasumično     -     " + (score/done*100) + "%";
	}
	document.getElementById("res").innerHTML = ""
}

function check(){
	var a = document.forms["input"]["ans"].value;
	cans = as[qst.indexOf(document.getElementById("ques").textContent)];

	if (a.replace(/\s/g, '').toLowerCase() == cans.replace(/\s/g, '').toLowerCase()){
		document.getElementById("res").innerHTML = "Vaš odgovor je točan"
		score += 1;
	}
	else{
		document.getElementById("res").innerHTML = "Vaš odgovor " + a + " je netočan. Točan odgoovor je " + cans;
	}
	done += 1;
	document.getElementById("del").click();	

	document.getElementById("ans").disabled = true;
}

function end(){
	document.getElementById("ques").innerHTML = "Osvježite stranicu kako biste krenuli ispočetka ili se okušajte u nekoj od ostalih kategorija";
	document.getElementById("fontup").innerHTML = "Nasumično     -     " + (score/qst.length*100) + "%";
	document.getElementById("res").innerHTML = "";
	document.getElementById("del").click();

	document.getElementById("btn").onclick = function(){};
}